'use client';
import Link from 'next/link';
import { useEffect, useState } from 'react';
import { ArrowDown, ArrowLeft, ArrowUp, Crown, RefreshCw, Sparkles, Trophy, TrendingUp, Users, Zap } from 'lucide-react';

const fmt=(n:number)=>new Intl.NumberFormat('id-ID').format(n);
const initials=(name:string)=>name.split(' ').filter(Boolean).map(x=>x[0]).slice(0,2).join('').toUpperCase();
type Row={entry:number;entry_name:string;player_name:string;rank:number;last_rank:number;total:number;event_total:number};
type Analytics={current:number|null;finishedGameweeks:number;movementReady:boolean;totalManagers:number;averageTotal:number;leader:Row|null;top10:Row[];risers:Row[];fallers:Row[];maxTotal:number;currentEvent:any};
export default function Analytics(){
 const [data,setData]=useState<Analytics|null>(null),[loading,setLoading]=useState(true),[error,setError]=useState('');
 const load=async()=>{setLoading(true);setError('');try{const r=await fetch('/api/analytics',{cache:'no-store'});const json=await r.json().catch(()=>null);if(!r.ok||!json?.ok)throw new Error(json?.error||`API error ${r.status}`);setData(json)}catch(e:any){setError(e?.message||'Analytics tidak dapat dimuat');setData(null)}finally{setLoading(false)}};
 useEffect(()=>{load()},[]);
 if(loading&&!data) return <main><section className="hero"><div className="container hero-inner"><Link href="/" className="back-link">← Kembali ke klasemen</Link><div className="profile-title"><div className="eyebrow">ERA SUPER LEAGUE • V5.5</div><h1>League Analytics</h1><p>Membaca momentum dan kekuatan klasemen dari seluruh manager.</p></div></div></section><div className="container page-shell"><div className="analytics-loading card">Memuat seluruh klasemen dan menghitung analytics…</div></div></main>;
 return <main><section className="hero"><div className="container hero-inner"><div className="hero-top"><div className="brand-pill"><Trophy size={15}/> ERA SUPER LEAGUE</div><div className="id-pill">LEAGUE ID <b>134820</b></div></div><div className="profile-title"><div className="eyebrow">2026 / 27 • V5.5 ANALYTICS</div><h1>League <span>Analytics</span></h1><p>Power ranking, riser/faller, dan snapshot performa seluruh peserta Era Super League. Movement ranking aktif mulai GW2.</p></div><div className="hero-meta"><span><i/> FPL Data</span><span>GW {data?.current??'—'}</span><span>{fmt(data?.totalManagers??0)} manager</span></div></div></section>
 <div className="container page-shell">{error&&<div className="card error-banner"><b>Analytics belum tersedia</b><span>{error}</span><button onClick={load}>Coba lagi</button></div>}<div className="analytics-toolbar"><Link href="/" className="back-link dark"><ArrowLeft size={14}/> Klasemen</Link><button onClick={load} disabled={loading}><RefreshCw size={14} className={loading?'spin':''}/> Refresh analytics</button></div>
 <div className="stats-grid"><Stat icon={<Users/>} value={fmt(data?.totalManagers??0)} label="Total manager"/><Stat icon={<Trophy/>} value={fmt(data?.averageTotal??0)} label="Rata-rata total poin"/><Stat icon={<Zap/>} value={fmt(data?.currentEvent?.average_entry_score??0)} label="Average GW"/><Stat icon={<Crown/>} value={fmt(data?.leader?.total??0)} label="Poin pemuncak"/></div>
 <div className="analytics-feature-grid"><section className="card feature-card"><div className="section-kicker">POWER RANKING</div><h2>Top 10 Era Super League</h2><p>Urutan berdasarkan overall rank resmi league.</p><div className="power-list">{data?.top10.map((r,i)=><Link href={`/manager/${r.entry}`} key={r.entry} className="power-row"><span className="power-pos">{String(i+1).padStart(2,'0')}</span><span className="avatar">{initials(r.player_name||r.entry_name)}</span><span className="power-name"><b>{r.player_name}</b><small>{r.entry_name}</small></span><span className="power-track"><i style={{width:`${Math.max(8,(r.total/(data?.maxTotal||1))*100)}%`}}/></span><strong>{fmt(r.total)}</strong></Link>)}</div></section>
 <section className="card feature-card"><div className="section-kicker">SEASON PULSE</div><h2>Momentum ranking</h2><p>Perubahan posisi sejak update klasemen sebelumnya.</p><div className="momentum-grid"><Momentum title="Biggest Riser" row={data?.risers?.[0]} up ready={data?.movementReady}/><Momentum title="Biggest Faller" row={data?.fallers?.[0]} ready={data?.movementReady}/></div><div className="pulse-note"><Sparkles size={15}/><span>Gunakan movement sebagai sinyal momentum, bukan pengganti analisis performa GW.</span></div></section></div>
 <div className="two-col"><section className="card feature-card"><div className="section-kicker">RISERS</div><h2>Biggest Riser</h2><p>Manager dengan lonjakan posisi terbesar.</p><div className="mini-list">{data?.movementReady ? data.risers.slice(0,6).map(r=><MiniRow key={r.entry} row={r} up/>):<div className="empty">Mulai tersedia setelah GW1.</div>}</div></section><section className="card feature-card"><div className="section-kicker">FALLERS</div><h2>Biggest Faller</h2><p>Manager dengan penurunan posisi terbesar.</p><div className="mini-list">{data?.movementReady ? data.fallers.slice(0,6).map(r=><MiniRow key={r.entry} row={r}/>):<div className="empty">Mulai tersedia setelah GW1.</div>}</div></section></div>
 <section className="card roadmap"><div><div className="section-kicker">V5.5 ANALYTICS</div><h2>Insight berikutnya</h2><p>Data layer V5.5 sudah diperkuat dengan server proxy, retry, pagination seluruh manager, dan ranking movement mulai GW2.</p></div><div className="roadmap-tags"><span>Captain</span><span>Chips</span><span>Transfers</span><span>GW Trend</span></div></section>
 <footer>ERA SUPER LEAGUE • Analytics V5 • League ID 134820 • Data from Fantasy Premier League</footer></div></main>
}
function Stat({icon,value,label}:{icon:any;value:string;label:string}){return <div className="stat card"><div className="stat-icon">{icon}</div><div className="stat-value">{value}</div><div className="stat-label">{label}</div></div>}
function Momentum({title,row,up=false,ready=false}:{title:string;row?:Row;up?:boolean;ready?:boolean}){const d=row?row.last_rank-row.rank:0;return <div className="momentum-card"><span>{title}</span>{!ready?<><b>Mulai tersedia GW2</b><small>Belum ada perbandingan ranking.</small></>:<><b>{row?.player_name||'—'}</b><small>{row?.entry_name||'—'}</small><strong className={up?'up':'down'}>{d>0?'↑':'↓'} {Math.abs(d)} posisi</strong></>}</div>}
function MiniRow({row,up=false}:{row:Row;up?:boolean}){const d=row.last_rank-row.rank;return <Link href={`/manager/${row.entry}`} className="mini-row"><span className="avatar">{initials(row.player_name||row.entry_name)}</span><span><b>{row.player_name}</b><small>{row.entry_name}</small></span><strong className={up?'up':'down'}>{up?'↑':'↓'} {Math.abs(d)}</strong></Link>}
